export const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';
export const DELETE_PRODUCT_RELOAD = 'DELETE_PRODUCT_RELOAD';

export const CREATE_PRODUCT_START = 'CREATE_PRODUCT_START';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const CREATE_PRODUCT_RELOAD = 'CREATE_PRODUCT_RELOAD';

export const UPDATE_PRODUCT_START = 'UPDATE_PRODUCT_START';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR= 'UPDATE_PRODUCT_ERROR';
export const UPDATE_PRODUCT_RELOAD = 'UPDATE_PRODUCT_RELOAD';

export const UPDATE_PRODUCT_DESCRIPTION = 'UPDATE_PRODUCT_DESCRIPTION';
export const UPDATE_PRODUCT_DESCRIPTION_SUCCESS = 'UPDATE_PRODUCT_DESCRIPTION_SUCCESS';
export const UPDATE_PRODUCT_DESCRIPTION_ERROR = 'UPDATE_PRODUCT_DESCRIPTION_ERROR';
export const UPDATE_PRODUCT_DESCRIPTION_RELOAD = 'UPDATE_PRODUCT_DESCRIPTION_RELOAD';
