export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTHENTICATE_FROM_MEMORY = 'AUTHENTICATE_FROM_MEMORY';
export const WITH_AUTHENTICATION = 'WITH_AUTHENTICATION';

export const REFRESH_TOKENS = 'REFRESH_TOKENS';
export const REFRESH_TOKENS_ERROR = 'REFRESH_TOKENS_ERROR';
export const REFRESH_TOKENS_SUCCESS = 'REFRESH_TOKENS_SUCCESS';
