export const AUTHENTICATE = 'AUTHENTICATE';
export const AUTH_ERROR = 'AUTH_FINISHED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const SAVE_TOKENS = 'SAVE_TOKENS';

export const AUTHENTICATE_FROM_MEMORY = 'AUTHENTICATE_FROM_MEMORY';
export const AUTHENTICATE_FROM_MEMORY_FINISH = 'AUTHENTICATE_FROM_MEMORY_FINISH';

export const WITH_AUTHENTICATION = 'WITH_AUTHENTICATION';

export const REFRESH_TOKENS = 'REFRESH_TOKENS';
export const REFRESH_TOKENS_ERROR = 'REFRESH_TOKENS_ERROR';
export const REFRESH_TOKENS_SUCCESS = 'REFRESH_TOKENS_SUCCESS';
