// @flow

export const REGISTER_START: 'START_REGISTER' = 'START_REGISTER';
export const REGISTER_ERROR: 'REGISTER_ERROR' = 'REGISTER_ERROR';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const FORGET_REGISTER_ERROR: 'FORGET_REGISTER_ERROR' = 'FORGET_REGISTER_ERROR';
